id: 1124
title: EPUB Language Identifier
status: active
type: utility
primary_language: python
languages:
  - python
tags:
  - epub
  - identifier
  - language
libraries:
  python:
    - bs4:BeautifulSoup
    - ebookatty:MetadataFetcher
    - ebooklib:epub
    - isbnlib
    - iso639:Lang
    - langdetect
    - pathlib:Path
    - re
    - __future__:annotations
    - argparse
    - collections:Counter
    - csv
    - dataclasses:dataclass
    - importlib.util
    - sys
    - tempfile
    - typing:Iterable
    - typing:Sequence
    - unittest
github:
  owner: Knarkoffer
  repo: epub-language-identifier
